# Generated by Django 2.2.16 on 2022-06-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220617_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='title', to='reviews.Genre', verbose_name='Категория произведения'),
        ),
    ]
