# Generated by Django 2.2.16 on 2022-06-17 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220617_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Оценка должна быть не меньше 1.'), django.core.validators.MaxValueValidator(10, 'Оценка должна быть не больше 10.')], verbose_name='Рейтинг'),
        ),
    ]
