# Generated by Django 2.2.16 on 2022-06-19 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220617_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальная оценка 1.'), django.core.validators.MaxValueValidator(10, 'Максимальная оценка 10.')], verbose_name='Рейтинг'),
        ),
    ]
